### ISSUE TITLE
Not showing in left-side plugin area

### ISSUE THREAD

**Issue by bogstandard** [EarToEarOak/SDRSharp-Net-Remote#1]
Hi, I'm having an issue where the plugin control panel is not showing in the plugin area on SDRSharp.

I've encountered this issue on both my Windows 10 installation & Windows 7 installation on an alternate machine. I've tried both the two latest releases on the GH page but have had no luck.

Are you able to help? It would be fantastic to get this working & build something from it.

Many Thanks,

Eric

**Comment by EarToEarOak** [comment]
Hello,
I think it might be due to SDRSharp upgrading to .NET 4.6, I'll try and update the plugin soon.

In the meantime you might have some luck if you install .NET 3.5.

**Comment by EarToEarOak** [comment]
I've updated the plugin to the new SDRSharp API (3ed76c3d3c19f6a93437d386bdb37e63c2c95dfc), fixing the problem you had.

The installer is available in the [releases section](https://github.com/EarToEarOak/SDRSharp-Net-Remote/releases)

**Comment by bogstandard** [comment]
No luck unfortunately (I hate being the guy who can't have the fixes work).

There's no panel showing still but an error/exception message is now displayed on attempting to close SDRSharp. The top lines are displayed below:

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SDRSharp.NetRemote.NetRemotePlugin.Close()
```

The plugin is noted further down the message though, so something is registering:

```
************** Loaded Assemblies **************
...
----------------------------------------
SDRSharp.NetRemote
    Assembly Version: 1.2.5768.25674
    Win32 Version: 1.2.5768.25674
    CodeBase: file:///C:/Users/eric/Desktop/radio/software/SDRSharp.NetRemote.DLL
----------------------------------------
```

I'm running Windows 10 & Windows 7 on an alternate machine both with the latest copies of SDR#, reverting the Windows 7 back to Net 3.5 didn't have any success, the earlier releases of your plugin were tried. 

In the meantime to wrangling for a fix for this (tinkering with the code myself & gratefully hoping you're able to provide a fix) I'm searching for a version of SDR# which is from before the shift in NET framework. I'll let you know if I'm able to get your plugin working either on the latest or the previous version.

Cheers for your help with this, I'll keep this issue thread updated if I've any successes. I hope the quoted exception error is some help.

**Comment by EarToEarOak** [comment]
The plugin now uses .NET 4.6 and the updated SDRSharp code so I'd recommend sticking to the latest version.
I've just tried tried it with 1416 which seemed fine, there was a shutdown problem with an earlier version though.

**Comment by bogstandard** [comment]
Hi, the latest release has fixed the issues I've been having.

Thanks for your efforts with this!

Cheers, Eric.

**Comment by EarToEarOak** [comment]
Not a problem, thanks for reporting the bugs!
