### ISSUE TITLE
Installer Issue - Lacking Ability to Set Install Folder

### ISSUE THREAD

**Issue by Lance-o-Rama** [EarToEarOak/SDRSharp-Net-Remote#4]
On the second page of the installer it says:

    **This plugin needs to be installed into the SDRSharp folder.**

    **Please select the location on the next page.**

The problem is, on the next page it only says "Click Install to continue with the installation", and does not allow me to set the location of the SDRSharp folder.  Since I have multiple installations of SDR# I really need to specify the path.

**Comment by EarToEarOak** [comment]
Thanks

I've just updated the setup script to prompt for a directory each time it is run (138c057b6b6bef77c857e4915e1a9bed682a5480).
The side effect is that the uninstall will only work with on the directory of the last setup.

**Comment by Lance-o-Rama** [comment]
That makes sense, that it would only remove the last directory. 

Thanks!  😄

☩ Lance

**Comment by EarToEarOak** [comment]
Glad to help!

**Comment by Lance-o-Rama** [comment]
I just downloaded v1.2.6169 and ran it. It didn't prompt me for the directory I wanted to install it from. 

Did I miss something?

☩ Lance

**Comment by EarToEarOak** [comment]
No you didn't!  Seems it didn't always work.

I've just uploaded a new one for you to try.
