### ISSUE TITLE
BUG: In parser class

### ISSUE THREAD

**Issue by thewraith2008** [EarToEarOak/SDRSharp-Net-Remote#5]
Hello.
Thank you for this plug-in for SDR#. I have found it to be most useful, allowing me to write my own programs to control SDR# via the plug-in. I've made a few changes to to code to suit my needs like adding more methods and the ability to change TCP port # so I can have more than one instance of SDR# under control.

Applies the Parser.cs from last commit '06af0ea' on 26 Oct 2015
The bug I speak of is in the 'Parser' class under the 'CmdFilterType'  function (Line 391)
Line 403 is `"result = Response<int>("FilterBandwidth", _control.FilterType);"`

`"FilterBandwidth"` should be `"FilterType"`

The result of  "Get" `"FilterType"` is returned under `"FilterBandwidth"`

Another thing is Line 54 `METHODS.Add("centerfrequency", CmdCentreFrequency);` is a duplicate of line 53.

Cheers.

**Comment by EarToEarOak** [comment]
Hello,
Thank you, I'm glad you find it useful.

I've removed the duplicate code in 52a1366e6a3e9b9b3d4f597c4bc8b2278f8882a6 and added network port selection in 618ce23229fc423e22ea60b3f23eb8e526ae8e0f
